### ISSUE TITLE
json data sample need update

### ISSUE THREAD

**Issue by NemTechCN** [nemtech/symbol-openapi#113]
https://nemtech.github.io/symbol-openapi/#operation/getAccountOutgoingTransactions  There are  difference between the actual data  and openapi sample.

**Comment by Vektrat** [comment]
please provide at least an actual example

**Comment by NemTechCN** [comment]
https://nemtech.github.io/symbol-openapi/#operation/getAccountIncomingTransactions ,  Should this sampleI change the transfer data to display "message, masaics", for example
`"recipientAddress": "989D52347D696567EF781D1519908B3FF1B42DC7BFCD5D6CB5",
		"message": {
			"type": 0,
			"payload": ""
		},
		"mosaics": [{
			"id": "2AB20419B4DA7D37",
			"amount": "1000"
		}]`

**Comment by dgarcia360** [comment]
Note that Symbol comes with multiple [transaction types](https://nemtech.github.io/concepts/transaction.html#transaction-types). The transfer transaction (with mosaics and messages) is just one of them, but there are others like AccountLinkTransaction, MosaicDefinitionTransaction, or NamespaceRegistrationTrasnaction. 

The response example by default shows the AccountLinkTransactionresponse because the transaction collection is in alphabetical order. To inspect the fields of other transaction types responses like Transfer Transaction, open "RESPONSE SCHEMA -> Array -> transaction, and select the desired type (e.g. TransferTransaction).

![image](https://user-images.githubusercontent.com/9107969/79206134-cf54db00-7e36-11ea-8760-2aebfc1eb97d.png)

**Comment by Vektrat** [comment]
we can close this issue since there is nothing wrong in this case
