### ISSUE TITLE
[TypeScript generator] undefined accountIds

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-openapi#19]
Originally reported by @rg911 

The rest sever only takes one public key or address after calling POST ``/account/``. In our current [DTO definition](https://github.com/nemtech/nem2-openapi/blob/master/spec/openapi3.yaml#L2827), we have both keys set as optional. 

The problem comes after generating the typescript client with [openapi-generator](https://github.com/OpenAPITools/openapi-generator). Although we provide only one of the ids, the other key is still in the model showing as ``undefined`` which causes the error.

Let's use the issue to discuss possible solutions.

**Comment by rg911** [comment]
There is a known issue on the openApi generator to handle `anyOf`. 
The options I can think of:
1. catapult-rest changes
  i. Split the endpoint to `...byPublicKeys` and `...byAddresses` this obviously need rest changes. (probably not a good idea)
  ii. Add `undefined` handler validator on rest
2. client side changes
  i. Manually 'patch` the generated code (currently on Java SDK)

My personal preference is let the Rest handle the `undefined` (or perhaps endpoint definition changes) so that we do not rely on manual hacks on generated codes, and also eliminate the dependancy against third party packages.

**Comment by Vektrat** [comment]
this is definitely undesired behaviour from the generator and i'm against enabling it by hacking our way up the tech stack

i'm not really a fan of having endpoints that accept multi-type params anyway (not the strict case, but originates from this exact case from the singular form of those endpoints), we at REST also have to do manual validation on this kind of OR because it's an exceptional case

i was going to suggest to duplicate endpoints to enable both types of parameter, but there's a lot of appearances, so this is out

the question, again, is, why are we supporting both requests by publicKey and address? what would be the problem with requesting everything, always, by address only? the address always exists, and it is always obtainable from public keys
